# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francisco/dev/binance_processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francisco/dev/binance_processor/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/dev/binance_processor/build/CMakeFiles /home/francisco/dev/binance_processor/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francisco/dev/binance_processor/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/francisco/dev/binance_processor/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named binance_processor

# Build rule for target.
binance_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binance_processor
.PHONY : binance_processor

# fast build rule for target.
binance_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/build
.PHONY : binance_processor/fast

src/core/globals.o: src/core/globals.cpp.o
.PHONY : src/core/globals.o

# target to build an object file
src/core/globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/globals.cpp.o
.PHONY : src/core/globals.cpp.o

src/core/globals.i: src/core/globals.cpp.i
.PHONY : src/core/globals.i

# target to preprocess a source file
src/core/globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/globals.cpp.i
.PHONY : src/core/globals.cpp.i

src/core/globals.s: src/core/globals.cpp.s
.PHONY : src/core/globals.s

# target to generate assembly for a file
src/core/globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/globals.cpp.s
.PHONY : src/core/globals.cpp.s

src/core/serialization.o: src/core/serialization.cpp.o
.PHONY : src/core/serialization.o

# target to build an object file
src/core/serialization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/serialization.cpp.o
.PHONY : src/core/serialization.cpp.o

src/core/serialization.i: src/core/serialization.cpp.i
.PHONY : src/core/serialization.i

# target to preprocess a source file
src/core/serialization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/serialization.cpp.i
.PHONY : src/core/serialization.cpp.i

src/core/serialization.s: src/core/serialization.cpp.s
.PHONY : src/core/serialization.s

# target to generate assembly for a file
src/core/serialization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/core/serialization.cpp.s
.PHONY : src/core/serialization.cpp.s

src/features/iceberg_detector.o: src/features/iceberg_detector.cpp.o
.PHONY : src/features/iceberg_detector.o

# target to build an object file
src/features/iceberg_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/iceberg_detector.cpp.o
.PHONY : src/features/iceberg_detector.cpp.o

src/features/iceberg_detector.i: src/features/iceberg_detector.cpp.i
.PHONY : src/features/iceberg_detector.i

# target to preprocess a source file
src/features/iceberg_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/iceberg_detector.cpp.i
.PHONY : src/features/iceberg_detector.cpp.i

src/features/iceberg_detector.s: src/features/iceberg_detector.cpp.s
.PHONY : src/features/iceberg_detector.s

# target to generate assembly for a file
src/features/iceberg_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/iceberg_detector.cpp.s
.PHONY : src/features/iceberg_detector.cpp.s

src/features/liquidity_tracker.o: src/features/liquidity_tracker.cpp.o
.PHONY : src/features/liquidity_tracker.o

# target to build an object file
src/features/liquidity_tracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/liquidity_tracker.cpp.o
.PHONY : src/features/liquidity_tracker.cpp.o

src/features/liquidity_tracker.i: src/features/liquidity_tracker.cpp.i
.PHONY : src/features/liquidity_tracker.i

# target to preprocess a source file
src/features/liquidity_tracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/liquidity_tracker.cpp.i
.PHONY : src/features/liquidity_tracker.cpp.i

src/features/liquidity_tracker.s: src/features/liquidity_tracker.cpp.s
.PHONY : src/features/liquidity_tracker.s

# target to generate assembly for a file
src/features/liquidity_tracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/liquidity_tracker.cpp.s
.PHONY : src/features/liquidity_tracker.cpp.s

src/features/trade_bucket_speed.o: src/features/trade_bucket_speed.cpp.o
.PHONY : src/features/trade_bucket_speed.o

# target to build an object file
src/features/trade_bucket_speed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/trade_bucket_speed.cpp.o
.PHONY : src/features/trade_bucket_speed.cpp.o

src/features/trade_bucket_speed.i: src/features/trade_bucket_speed.cpp.i
.PHONY : src/features/trade_bucket_speed.i

# target to preprocess a source file
src/features/trade_bucket_speed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/trade_bucket_speed.cpp.i
.PHONY : src/features/trade_bucket_speed.cpp.i

src/features/trade_bucket_speed.s: src/features/trade_bucket_speed.cpp.s
.PHONY : src/features/trade_bucket_speed.s

# target to generate assembly for a file
src/features/trade_bucket_speed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/features/trade_bucket_speed.cpp.s
.PHONY : src/features/trade_bucket_speed.cpp.s

src/io/binance_connector.o: src/io/binance_connector.cpp.o
.PHONY : src/io/binance_connector.o

# target to build an object file
src/io/binance_connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/binance_connector.cpp.o
.PHONY : src/io/binance_connector.cpp.o

src/io/binance_connector.i: src/io/binance_connector.cpp.i
.PHONY : src/io/binance_connector.i

# target to preprocess a source file
src/io/binance_connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/binance_connector.cpp.i
.PHONY : src/io/binance_connector.cpp.i

src/io/binance_connector.s: src/io/binance_connector.cpp.s
.PHONY : src/io/binance_connector.s

# target to generate assembly for a file
src/io/binance_connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/binance_connector.cpp.s
.PHONY : src/io/binance_connector.cpp.s

src/io/mmap_buffer.o: src/io/mmap_buffer.cpp.o
.PHONY : src/io/mmap_buffer.o

# target to build an object file
src/io/mmap_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/mmap_buffer.cpp.o
.PHONY : src/io/mmap_buffer.cpp.o

src/io/mmap_buffer.i: src/io/mmap_buffer.cpp.i
.PHONY : src/io/mmap_buffer.i

# target to preprocess a source file
src/io/mmap_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/mmap_buffer.cpp.i
.PHONY : src/io/mmap_buffer.cpp.i

src/io/mmap_buffer.s: src/io/mmap_buffer.cpp.s
.PHONY : src/io/mmap_buffer.s

# target to generate assembly for a file
src/io/mmap_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/mmap_buffer.cpp.s
.PHONY : src/io/mmap_buffer.cpp.s

src/io/ring_buffer_consumer.o: src/io/ring_buffer_consumer.cpp.o
.PHONY : src/io/ring_buffer_consumer.o

# target to build an object file
src/io/ring_buffer_consumer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/ring_buffer_consumer.cpp.o
.PHONY : src/io/ring_buffer_consumer.cpp.o

src/io/ring_buffer_consumer.i: src/io/ring_buffer_consumer.cpp.i
.PHONY : src/io/ring_buffer_consumer.i

# target to preprocess a source file
src/io/ring_buffer_consumer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/ring_buffer_consumer.cpp.i
.PHONY : src/io/ring_buffer_consumer.cpp.i

src/io/ring_buffer_consumer.s: src/io/ring_buffer_consumer.cpp.s
.PHONY : src/io/ring_buffer_consumer.s

# target to generate assembly for a file
src/io/ring_buffer_consumer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/io/ring_buffer_consumer.cpp.s
.PHONY : src/io/ring_buffer_consumer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binance_processor.dir/build.make CMakeFiles/binance_processor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... binance_processor"
	@echo "... src/core/globals.o"
	@echo "... src/core/globals.i"
	@echo "... src/core/globals.s"
	@echo "... src/core/serialization.o"
	@echo "... src/core/serialization.i"
	@echo "... src/core/serialization.s"
	@echo "... src/features/iceberg_detector.o"
	@echo "... src/features/iceberg_detector.i"
	@echo "... src/features/iceberg_detector.s"
	@echo "... src/features/liquidity_tracker.o"
	@echo "... src/features/liquidity_tracker.i"
	@echo "... src/features/liquidity_tracker.s"
	@echo "... src/features/trade_bucket_speed.o"
	@echo "... src/features/trade_bucket_speed.i"
	@echo "... src/features/trade_bucket_speed.s"
	@echo "... src/io/binance_connector.o"
	@echo "... src/io/binance_connector.i"
	@echo "... src/io/binance_connector.s"
	@echo "... src/io/mmap_buffer.o"
	@echo "... src/io/mmap_buffer.i"
	@echo "... src/io/mmap_buffer.s"
	@echo "... src/io/ring_buffer_consumer.o"
	@echo "... src/io/ring_buffer_consumer.i"
	@echo "... src/io/ring_buffer_consumer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/francisco/dev/binance_processor/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

